import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {getToken} from '/Users/davesmacbookpro/.npm/_npx/da5c1b6ea715e8b4/node_modules/netlify-cli/dist/utils/command-helpers.js';
const [token]=await getToken();assert(token);const root=new URL('./',import.meta.url);const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function site(id){const r=await fetch('https://api.netlify.com/api/v1/sites/'+id,{headers:{Authorization:'Bearer '+token}});assert.equal(r.status,200);const s=await r.json();return {id:s.id,name:s.name,url:s.ssl_url,deploy:s.published_deploy.id,repo:s.build_settings.repo_path,branch:s.build_settings.repo_branch};}
async function asset(base,path){const r=await fetch(base+path,{headers:{'Cache-Control':'no-cache'}});return {path,status:r.status,sha256:hash(Buffer.from(await r.arrayBuffer()))};}
const [staging,production]=await Promise.all([site('071b252e-a922-4846-a784-8dca1edad377'),site('ece0f6f3-6c3d-46e6-bb51-95ce1ccefb06')]);assert.equal(staging.name,'revitalizedacademy-staging');assert.equal(staging.branch,'codex/staging');
const previous=JSON.parse(fs.readFileSync(new URL('../2026-10-05-vitality-resume/deployment-before.json',import.meta.url)));
const productionFiles=await Promise.all(previous.productionFiles.map(f=>asset('https://revitalizedacademy.com',f.path)));assert.equal(production.deploy,previous.production.deploy);assert.deepEqual(productionFiles,previous.productionFiles);
const phase=process.argv[2]||'before';let assets=[];
if(phase==='before'){const r=await fetch(staging.url+'/runtime-config.js');assert.equal(r.status,200);fs.writeFileSync(new URL('runtime-before.js',root),await r.text());}
else {const before=JSON.parse(fs.readFileSync(new URL('deployment-before.json',root)));assert.equal(production.deploy,before.production.deploy);const paths=['/consult.html','/js/vitality55.js?v=resume-2','/js/vitality-resume.js?v=2','/css/vitality55.css?v=87','/runtime-config.js'];assets=await Promise.all(paths.map(p=>asset(staging.url,p)));for(const a of assets){assert.equal(a.status,200);assert.equal(a.sha256,hash(fs.readFileSync('dist'+a.path.split('?')[0])));}}
fs.writeFileSync(new URL('deployment-'+phase+'.json',root),JSON.stringify({at:new Date().toISOString(),staging,production,productionFiles,assets},null,2)+'\n');console.log(JSON.stringify({staging,production,exactAssets:assets.length,productionUnchanged:true}));
