import {JSDOM} from 'jsdom';import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {getToken} from '/Users/davesmacbookpro/.npm/_npx/da5c1b6ea715e8b4/node_modules/netlify-cli/dist/utils/command-helpers.js';
const [token]=await getToken();assert(token);const root=new URL('./',import.meta.url);const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function site(id){const r=await fetch('https://api.netlify.com/api/v1/sites/'+id,{headers:{Authorization:'Bearer '+token}});assert.equal(r.status,200);const s=await r.json();return {id:s.id,name:s.name,url:s.ssl_url,deploy:s.published_deploy.id,repo:s.build_settings.repo_path,branch:s.build_settings.repo_branch};}
async function asset(base,path){const r=await fetch(base+path,{headers:{'Cache-Control':'no-cache'}});return {path,status:r.status,sha256:hash(Buffer.from(await r.arrayBuffer()))};}
const [staging,production]=await Promise.all([site('071b252e-a922-4846-a784-8dca1edad377'),site('ece0f6f3-6c3d-46e6-bb51-95ce1ccefb06')]);assert.equal(staging.name,'revitalizedacademy-staging');assert.equal(staging.branch,'codex/staging');
const previous=JSON.parse(fs.readFileSync(new URL('../2026-10-05-vitality-resume/deployment-before.json',import.meta.url)));
const productionFiles=await Promise.all(previous.productionFiles.map(f=>asset('https://revitalizedacademy.com',f.path)));assert.equal(production.deploy,previous.production.deploy);assert.deepEqual(productionFiles,previous.productionFiles);
const phase=process.argv[2]||'before';let assets=[],htmlComparison=null;
if(phase==='before'){const r=await fetch(staging.url+'/runtime-config.js');assert.equal(r.status,200);fs.writeFileSync(new URL('runtime-before.js',root),await r.text());}
else {const before=JSON.parse(fs.readFileSync(new URL('deployment-before.json',root)));assert.equal(production.deploy,before.production.deploy);const paths=['/js/vitality55.js?v=resume-2','/js/vitality-resume.js?v=2','/css/vitality55.css?v=87','/runtime-config.js'];assets=await Promise.all(paths.map(p=>asset(staging.url,p)));for(const a of assets){assert.equal(a.status,200);assert.equal(a.sha256,hash(fs.readFileSync('dist'+a.path.split('?')[0])));}
const r=await fetch(staging.url+'/consult.html');assert.equal(r.status,200);const text=await r.text(),built=fs.readFileSync('dist/consult.html','utf8');const live=new JSDOM(text).window.document,expected=new JSDOM(built).window.document;
const controls=d=>Array.from(d.querySelectorAll('form'),f=>({name:f.getAttribute('name'),method:f.getAttribute('method'),fields:Array.from(f.querySelectorAll('input,select,textarea,button'),e=>({tag:e.tagName,name:e.getAttribute('name'),type:e.getAttribute('type'),value:e.getAttribute('value'),required:e.required,disabled:e.disabled,text:e.tagName==='BUTTON'?e.textContent:null}))}));
const scripts=d=>Array.from(d.querySelectorAll('script'),e=>({src:e.getAttribute('src'),text:e.textContent}));
assert.deepEqual(controls(live),controls(expected));assert.deepEqual(scripts(live),scripts(expected));assert.equal(live.querySelector('main').textContent,expected.querySelector('main').textContent);
htmlComparison={status:r.status,formsAndControlsMatch:true,scriptSourcesAndInlineCodeMatch:true,mainTextMatches:true,rawHashMatch:hash(text)===hash(built),difference:'Existing Netlify clean-link and Forms attribute processing; application text, fields and scripts match'};
}
fs.writeFileSync(new URL('deployment-'+phase+'.json',root),JSON.stringify({at:new Date().toISOString(),staging,production,productionFiles,assets,htmlComparison},null,2)+'\n');console.log(JSON.stringify({staging,production,exactAssets:assets.length,productionUnchanged:true}));
