const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{JSDOM}=require('jsdom');
const {resolve,paymentUrl}=require('../js/environment.js'),{config,deploymentGuard}=require('../scripts/staging/config.cjs'),{build}=require('../scripts/build-site.cjs'),{validateTarget,legalInputs}=require('../scripts/staging/provision.cjs');
const input={environment:'staging',supabaseUrl:'https://abcdefghijklmnopqrst.supabase.co',supabaseKey:'sb_publishable_synthetic',appOrigin:'https://stage.example.invalid',paymentMode:'synthetic'};
const env={RVA_ENVIRONMENT:input.environment,RVA_SUPABASE_URL:input.supabaseUrl,RVA_SUPABASE_PUBLISHABLE_KEY:input.supabaseKey,RVA_APP_ORIGIN:input.appOrigin,RVA_PAYMENT_MODE:input.paymentMode};
test('production mapping resolves to the known publishable project and branded recovery',()=>{const c=config({RVA_ENVIRONMENT:'production'});assert.equal(c.projectRef,'voalfpxiyznnqfcqcymd');assert.equal(c.recoveryRedirect,'https://revitalizedacademy.com/portal/password-reset.html');});
for(const [name,patch]of Object.entries({project:{supabaseUrl:'https://voalfpxiyznnqfcqcymd.supabase.co'},origin:{appOrigin:'https://revitalizedacademy.com'},www:{appOrigin:'https://www.revitalizedacademy.com'},alias:{appOrigin:'https://revitalizedacademy.netlify.app'},edge:{edgeBaseUrl:'https://voalfpxiyznnqfcqcymd.supabase.co/functions/v1'},callback:{notificationOrigin:'https://revitalizedacademy.com'},recovery:{recoveryOrigin:'https://revitalizedacademy.com'},secret:{supabaseKey:'sb_secret_never_public'},money:{paymentMode:'live'},incomplete:{supabaseKey:''}}))test('staging rejects unsafe '+name,()=>assert.throws(()=>resolve({...input,...patch})));
test('service-role JWT is rejected while matching legacy anon JWT is allowed',()=>{const key=p=>'header.'+Buffer.from(JSON.stringify(p)).toString('base64url')+'.signature';assert.throws(()=>resolve({...input,supabaseKey:key({role:'service_role',ref:'abcdefghijklmnopqrst'})}));assert.equal(resolve({...input,supabaseKey:key({role:'anon',ref:'abcdefghijklmnopqrst'})}).environment,'staging');});
test('all staging callbacks, signer invitations and recovery remain on its approved origin',()=>{const c=resolve(input);for(const k of ['onboardingUrl','signupRedirect','recoveryRedirect','staffRedirect','signerUrl'])assert.equal(new URL(c[k]).origin,input.appOrigin,k);});
test('staging supports an exact technical fallback while all generated links use the primary branded origin',()=>{const fallback='https://revitalizedacademy-staging.netlify.app',c=resolve({...input,appOrigin:'https://beta.revitalizedacademy.com',fallbackOrigins:[fallback]});assert.deepEqual(c.allowedOrigins,['https://beta.revitalizedacademy.com',fallback]);for(const k of ['onboardingUrl','signupRedirect','recoveryRedirect','staffRedirect','signerUrl'])assert.equal(new URL(c[k]).origin,'https://beta.revitalizedacademy.com',k);assert.throws(()=>resolve({...input,fallbackOrigins:['https://revitalizedacademy.com']}));});
test('dedicated temporary Netlify hostname needs only config',()=>assert.equal(resolve({...input,appOrigin:'https://rva-staging-example.netlify.app'}).signupRedirect,'https://rva-staging-example.netlify.app/member/onboarding/'));
test('synthetic payments never expose a checkout endpoint; production retains HTTPS behavior',()=>{assert.equal(paymentUrl('https://live-payment.invalid',resolve(input)),null);assert.equal(paymentUrl('https://provider.invalid',config({RVA_ENVIRONMENT:'production'})),'https://provider.invalid/');assert.equal(paymentUrl('javascript:alert(1)',config({RVA_ENVIRONMENT:'production'})),null);});
test('Netlify wrong site, branch, preview context and origin all fail before build',()=>{const good={NETLIFY:'true',SITE_ID:'stage-id',RVA_EXPECTED_NETLIFY_SITE_ID:'stage-id',URL:input.appOrigin,CONTEXT:'production',BRANCH:'codex/staging'};deploymentGuard(resolve(input),good);for(const patch of [{SITE_ID:'prod-id'},{BRANCH:'main'},{CONTEXT:'deploy-preview'},{URL:'https://revitalizedacademy.com'}])assert.throws(()=>deploymentGuard(resolve(input),{...good,...patch}));});
test('staging database target refuses production, wrong ref, unverified TLS and existing generic hosts',()=>{const c=resolve(input),good={RVA_STAGING_PROJECT_REF:c.projectRef,RVA_STAGING_DATABASE_URL:'postgresql://postgres@db.'+c.projectRef+'.supabase.co/postgres?sslmode=verify-full'};assert(validateTarget(good,c));for(const value of ['postgresql://postgres@db.voalfpxiyznnqfcqcymd.supabase.co/postgres?sslmode=verify-full','postgresql://postgres@localhost/postgres',good.RVA_STAGING_DATABASE_URL.replace('verify-full','require')])assert.throws(()=>validateTarget({...good,RVA_STAGING_DATABASE_URL:value},c));});
test('runtime rejects staging config on an unapproved hostname and never initializes a client',()=>{const dom=new JSDOM('<body></body>',{url:'https://revitalizedacademy.com',runScripts:'outside-only'});dom.window.RVA_PUBLIC_CONFIG=input;assert.throws(()=>dom.window.eval(fs.readFileSync('js/environment.js','utf8')),/host is not allowed/);assert.equal(dom.window.RVA_ENV,undefined);dom.window.close();});
test('runtime accepts only the configured staging fallback hostname',()=>{const fallback='https://revitalizedacademy-staging.netlify.app',dom=new JSDOM('<body></body>',{url:fallback,runScripts:'outside-only'});dom.window.RVA_PUBLIC_CONFIG={...input,appOrigin:'https://beta.revitalizedacademy.com',fallbackOrigins:[fallback]};dom.window.eval(fs.readFileSync('js/environment.js','utf8'));assert.equal(dom.window.RVA_ENV.appOrigin,'https://beta.revitalizedacademy.com');assert(dom.window.RVA_ENV.allowedOrigins.includes(fallback));dom.window.close();});
test('built runtime preserves the exact staging fallback hostname',()=>{const fallback='https://revitalizedacademy-staging.netlify.app',dir=fs.mkdtempSync(path.join(os.tmpdir(),'rva-fallback-artifact-'));try{build({...env,RVA_APP_ORIGIN:'https://beta.revitalizedacademy.com',RVA_FALLBACK_ORIGINS:fallback},dir);const dom=new JSDOM('<body></body>',{url:fallback,runScripts:'outside-only'});dom.window.eval(fs.readFileSync(path.join(dir,'runtime-config.js'),'utf8'));assert.deepEqual([...dom.window.RVA_PUBLIC_CONFIG.fallbackOrigins],[fallback]);dom.window.eval(fs.readFileSync(path.join(dir,'js/environment.js'),'utf8'));assert(dom.window.RVA_ENV.allowedOrigins.includes(fallback));dom.window.close();}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('artifact is an exact public allowlist and never contains backend/private/secret artifacts',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rva-artifact-'));try{const result=build({...env,SUPABASE_SERVICE_ROLE_KEY:'sb_secret_CANARY',RESEND_API_KEY:'re_CANARY'},dir);const files=fs.readdirSync(dir,{recursive:true}).filter(f=>fs.statSync(path.join(dir,f)).isFile());assert.equal(files.length,result.files);
 for(const f of files){assert(!/^(supabase|docs|tests|scripts|config|site-build|\.staging-private|node_modules)\//.test(f),f);assert(!/\.sql$|evidence\.json|AGENTS|SECURITY_MODEL/.test(f));if(/\.(js|json|html)$/.test(f)){const text=fs.readFileSync(path.join(dir,f),'utf8');assert(!text.includes('sb_secret_CANARY')&&!text.includes('re_CANARY'));assert(!text.includes('sb_secret_')||f==='js/environment.js');}}
 for(const file of ['consult.html','webinar.html','member/index.html','member/onboarding/index.html','portal/password-reset.html']){const html=fs.readFileSync(path.join(dir,file),'utf8');assert(html.indexOf('/runtime-config.js')<html.indexOf('/js/environment.js'));}
 const consult=new JSDOM(fs.readFileSync(path.join(dir,'consult.html'),'utf8')).window.document;assert(consult.querySelector('form[data-netlify]'));
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('artifact preserves local script/style/image dependencies referenced by public pages',()=>{const manifest=new Set(require('../config/public-files.json'));const missing=[];for(const f of manifest){if(!f.endsWith('.html'))continue;const d=new JSDOM(fs.readFileSync(f,'utf8')).window.document;for(const e of d.querySelectorAll('script[src],img[src],link[rel="stylesheet"][href]')){const v=(e.getAttribute('src')||e.getAttribute('href')).split(/[?#]/)[0];if(/^(https?:|data:|\/\/)/.test(v))continue;const target=path.posix.normalize(v.startsWith('/')?v.slice(1):path.posix.join(path.posix.dirname(f),v));if(!manifest.has(target))missing.push(f+': '+target);}}assert.deepEqual(missing,['outreach.html: assets/css/styles.css','outreach.html: assets/images/logo-gold.png','outreach.html: assets/images/outreach-bikes-20260807.jpg','outreach.html: assets/images/outreach-community-20260807.jpg','outreach.html: assets/images/outreach-connection-20260807.jpg','outreach.html: assets/images/footer-raise-reign-reach.png','outreach.html: assets/js/site.js']); /* These seven dependencies are already absent at feef92e; preserve and report the existing gap. */});
test('no production bindings remain in application callers',()=>{for(const file of require('../config/public-files.json'))if(file.endsWith('.js')&&file!=='js/environment.js')assert.doesNotMatch(fs.readFileSync(file,'utf8'),/voalfpxiyznnqfcqcymd|sb_publishable_09WC/);});
test('legal manifest records exact recovered hashes and protected seed input is never deployable',()=>{const m=require('../config/legal-manifest.json');assert.deepEqual(m.map(x=>x.version),['MK7','MK.1']);assert(m.every(x=>/^[a-f0-9]{64}$/.test(x.content_hash)&&/^[a-f0-9]{64}$/.test(x.pdf_sha256)));assert(!require('../config/public-files.json').some(x=>/legal|contract-mk7|nda-mk1/.test(x)));});
test('first-step bridge uses staging endpoint and cannot cancel independent Netlify capture on mirror failure',async()=>{const dom=new JSDOM('<form data-vitality-lead-form><input name="first_name" value="Synthetic"><input name="last_name" value="Adult"><input name="email" value="synthetic@example.invalid"><input name="phone" value="5550100"></form>',{url:input.appOrigin,runScripts:'outside-only'});const calls=[];dom.window.RVA_PUBLIC_CONFIG=input;dom.window.eval(fs.readFileSync('js/environment.js','utf8'));dom.window.fetch=async(url,options)=>{calls.push({url,options});throw Error('Synthetic mirror unavailable');};dom.window.eval(fs.readFileSync('js/revitalized-data.js','utf8'));const event=new dom.window.Event('submit',{bubbles:true,cancelable:true});dom.window.document.querySelector('form').dispatchEvent(event);await new Promise(r=>setImmediate(r));assert.equal(event.defaultPrevented,false);assert.equal(calls.length,1);assert.equal(calls[0].url,input.supabaseUrl+'/functions/v1/public-intake');assert.equal(JSON.parse(calls[0].options.body).first_name,'Synthetic');dom.window.close();});
test('invalid legal bytes fail before a database connection',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'rva-legal-'));try{fs.writeFileSync(path.join(d,'templates.json'),JSON.stringify(require('../config/legal-manifest.json').map(r=>({...r,content_text:'changed'}))));assert.throws(()=>legalInputs(d),/content hash mismatch/);}finally{fs.rmSync(d,{recursive:true,force:true});}});

test('unknown config fields cannot enter the public resolved object',()=>{const c=resolve({...input,SUPABASE_SERVICE_ROLE_KEY:'secret',providerToken:'secret'});assert.equal(c.SUPABASE_SERVICE_ROLE_KEY,undefined);assert.equal(c.providerToken,undefined);});
