// Exact production-built UI with isolated public food fixtures; all network aborted.
const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require(process.env.RVA_PLAYWRIGHT_PATH||'playwright');
const {normalize}=require('../netlify/lib/fooddata.cjs'),source=require('./fixtures/usda-foods.json').foods;
const read=f=>fs.readFileSync('production-dist/'+f,'utf8');
const catalog=Array.from(fs.readFileSync('supabase/migrations/20261006164158_production_durable_content.sql','utf8').matchAll(/\('([^']+)','([^']+)','([^']+)','([^']+)',(true|false),(\d+)\)/g),m=>({nutrient_key:m[1],name:m[2],category:m[3],unit:m[4],active:true,default_visible:m[5]==='true',sort_order:Number(m[6])}));
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.RVA_CHROMIUM_EXECUTABLE});let checks=0;const errors=[];
 try{
  const page=await browser.newPage();await page.route('**/*',r=>r.abort());page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type())&&!m.text().includes('net::ERR_FAILED'))errors.push(m.text());});
  await page.route('https://revitalizedacademy.com/**',r=>r.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><body></body></html>'}));await page.goto('https://revitalizedacademy.com/portal/');
  await page.setContent(read('portal/index.html').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link[^>]*>/gi,''));
  for(const f of ['portal.css','portal-polish.css','portal-shell.css','portal-programs.css','portal-food-database.css'])await page.addStyleTag({content:read('portal/'+f)});
  await page.evaluate(({foods,catalog})=>{
   document.getElementById('auth-view').classList.add('hidden');document.getElementById('portal-view').classList.remove('hidden');window.allowed=true;window.role='owner';window.ops=[];window.RVA_PUBLIC_CONFIG={environment:'production',projectRef:'voalfpxiyznnqfcqcymd'};
   const foodsLocal=foods.map((f,i)=>({...f,id:'food'+i,provider:'usda_fdc',methodology_id:'method',active:false,serving_size:100,serving_unit:'g',grams_per_serving:100}));foodsLocal.push({id:'custom',name:'Custom Food',methodology_id:'method',nutrition:{protein_g:0},grams_per_serving:20,serving_unit:'serving',serving_size:1});
   const rows={program_catalog:[{program_code:'total-wellness-12',name:'12-Month Intensive',program_type:'coaching',active:true,metadata:{support_model:'Highest-Touch Private + Group Coaching'}}],program_entitlement_templates:[{id:'benefit',program_code:'total-wellness-12',entitlement_key:'video',label:'Private Video Coaching Session With Justyn & Elle',limit_value:1,active:true}],nutrition_methodologies:[{id:'method',name:'Existing Methodology',status:'draft'}],nutrition_nutrient_catalog:catalog,food_catalog:foodsLocal,recipes:[{id:'recipe',methodology_id:'method',title:'Smoothie',servings:2,status:'draft',nutrition:{protein_g:10},nutrition_calculated_at:'2026-10-07',nutrition_calculation_meta:{complete:true,recipe_total:{protein_g:20},total_recipe_weight_grams:200}}],recipe_ingredients:[{id:'ingredient',recipe_id:'recipe',food_id:'food0',ingredient:foods[0].name,quantity:100,unit:'g',weight_grams:null}]};
   const db={from(table){let filters=[],single=false,mutation;const q={select(){return q},order(){return q},limit(){return q},eq(k,v){filters.push([k,v]);return q},single(){single=true;return q},maybeSingle(){single=true;return q},insert(v){mutation=['insert',v];return q},update(v){mutation=['update',v];return q},delete(){mutation=['delete',null];return q},then(resolve){let items=(rows[table]||[]).filter(row=>filters.every(([k,v])=>row[k]===v));if(mutation){window.ops.push({table,mutation});if(mutation[0]==='update')items.forEach(row=>Object.assign(row,mutation[1]));items=[{id:'saved'}];}return Promise.resolve({data:single?items[0]||null:items,error:null}).then(resolve)}};return q},auth:{getSession:async()=>({data:{session:{access_token:'local-only'}}})},rpc:async(name,args)=>{window.ops.push({rpc:name,args});if(name==='set_food_revitalized_approved')foodsLocal.find(f=>f.id===args.p_food).revitalized_approved=args.p_approved;return {data:{complete:true},error:null}}};
   window.RA_PORTAL={authClient:db,currentUserId:()=> 'local-owner',currentStaffRole:()=>window.role,hasPermission:()=>window.allowed,permissions:()=>({'learning.manage':window.allowed}),showStatus:(n,t)=>{if(n)n.textContent=t},titleCase:s=>s,formatDate:s=>s};
   window.fetch=async(url,o)=>{const b=JSON.parse(o.body);window.ops.push({api:b.action});if(b.records)return{ok:true,json:async()=>({status:'complete',records:3,message:'Synced to Beta.'})};if(b.action==='search')return{ok:true,json:async()=>({foods:foods.map(f=>({fdcId:f.fdc_id,name:f.name,type:f.source_data_type,brand:f.brand}))})};if(b.action==='details')return{ok:true,json:async()=>({foods:foods.filter(f=>b.ids.includes(f.fdc_id))})};return{ok:true,json:async()=>({food:foodsLocal.find(f=>f.fdc_id===b.fdcId)})};};
  },{foods:source.map(normalize),catalog});
  for(const f of ['portal-shell.js','portal-programs.js','portal-recipe-builder.js','portal-food-database.js','portal-content-sync.js'])await page.addScriptTag({content:read('portal/'+f)});
  await page.waitForSelector('.program-access-card',{state:'attached'});
  const overflow=async selector=>{assert(await page.evaluate(selector=>{const d=document.querySelector(selector);return d.scrollWidth<=d.clientWidth+1&&document.documentElement.scrollWidth<=innerWidth+1},selector),selector+' overflow');checks++;};
  for(const size of [{width:1440,height:1000},{width:768,height:1024},{width:390,height:844}]){
   await page.setViewportSize(size);
   await page.evaluate(()=>document.querySelector('.ra-sidebar button[data-target="#program-access-panel"]').click());await overflow('#program-access-list');
   await page.evaluate(()=>{document.querySelector('.ra-sidebar button[data-target="#program-content-panel"]').click();document.querySelector('[data-program-content="foods"]').click();});
   assert.equal(await page.getByText('Search Food Database',{exact:true}).count(),1);checks++;
   await page.getByText('Search Food Database',{exact:true}).click();await page.getByRole('searchbox',{name:'Food name'}).fill('apple');await page.locator('.food-database-search button').click();await page.waitForSelector('.food-database-result');
   assert.equal(await page.locator('.food-database-result').count(),5);checks++;await page.locator('.food-database-result button').first().click();await page.waitForSelector('[data-food-detail]');assert((await page.locator('[data-food-detail]').innerText()).includes('140 g'));checks++;await overflow('.food-database-dialog');await page.screenshot({path:'/private/tmp/rva-fooddata-search-'+size.width+'.png'});
   await page.locator('.food-database-dialog select[aria-label="Import into existing nutrition methodology"]').selectOption('method');await page.getByText('Use this food',{exact:true}).click();await page.waitForSelector('.food-database-modal',{state:'detached'});
   await page.locator('#program-content-list').getByText('★ Mark ReVitalized Approved',{exact:true}).first().click();await page.locator('#food-database-tools select').selectOption('approved');assert((await page.locator('#program-content-list').innerText()).includes('★ ReVitalized Approved'));checks++;
   for(const [value,text]of [['branded','Branded Database Food'],['custom','ReVitalized Custom Food'],['usda','USDA Database Food']]){await page.locator('#food-database-tools select').selectOption(value);assert((await page.locator('#program-content-list').innerText()).includes(text));checks++;}
   await page.locator('#food-database-tools select').selectOption('all');await overflow('#program-content-list');
   await page.getByText('Sync to Beta',{exact:true}).first().click();await overflow('.food-database-dialog');await page.getByText('Close',{exact:true}).click();
   const priorRefresh=await page.evaluate(()=>window.ops.filter(o=>o.api==='refresh').length);
   await page.locator('#program-content-list').getByText('Refresh from Source',{exact:true}).first().click();await overflow('.food-database-dialog');
   await page.locator('.food-database-dialog').getByText('Cancel',{exact:true}).click();assert.equal(await page.evaluate(()=>window.ops.filter(o=>o.api==='refresh').length),priorRefresh);checks++;
   await page.locator('#program-content-list').getByText('Refresh from Source',{exact:true}).first().click();await page.getByText('Confirm Source Refresh',{exact:true}).click();await page.waitForSelector('.food-database-modal',{state:'detached'});
   assert.equal(await page.evaluate(()=>window.ops.filter(o=>o.api==='refresh').length),priorRefresh+1);assert((await page.locator('#food-library-status').innerText()).includes('recipe snapshots are unchanged'));checks++;

   await page.locator('#program-content-list').getByText('Edit',{exact:true}).first().click();await page.waitForTimeout(40);assert(await page.locator('#program-content-title-input').isDisabled());assert(await page.locator('[data-nutrient-key="protein_g"]').isDisabled());checks++;
   await page.locator('#content-category').fill('Produce');await page.locator('#program-content-form [type="submit"]').click();await page.waitForSelector('#program-content-modal',{state:'hidden'});
   assert(await page.evaluate(()=>{const p=window.ops.filter(o=>o.table==='food_catalog'&&o.mutation?.[0]==='update').at(-1)?.mutation[1];return p?.category==='Produce'&&!('nutrition' in p)&&!('name' in p)&&!('grams_per_serving' in p);}));checks++;
   await page.evaluate(()=>window.RA_RECIPE_BUILDER.open({id:'recipe',methodology_id:'method',title:'Smoothie'}));await page.waitForSelector('.recipe-builder-ingredient');await page.locator('#recipe-builder-food').selectOption('food2');assert(await page.locator('#recipe-builder-unit option').count()>2);checks++;
   await page.locator('.recipe-builder-ingredient-actions input').fill('200');await page.getByText('Save quantity',{exact:true}).click();await page.waitForTimeout(40);assert(await page.evaluate(()=>window.ops.some(o=>o.table==='recipe_ingredients'&&o.mutation?.[1]?.quantity===200)));checks++;
   await overflow('.recipe-builder-dialog');await page.locator('#recipe-builder-search').click();assert(await page.locator('.food-database-modal').count());checks++;await overflow('.food-database-dialog');await page.locator('.food-database-dialog').getByText('Close',{exact:true}).click();await page.evaluate(()=>window.RA_RECIPE_BUILDER.close());
  }
  await page.evaluate(()=>{window.role='coach';window.RA_PROGRAM_CONTENT.render();});assert.equal(await page.locator('#program-content-list').getByText('★ Mark ReVitalized Approved',{exact:true}).count(),0);checks++;
  await page.evaluate(()=>window.RA_FOOD_DATABASE.open());await page.evaluate(()=>document.dispatchEvent(new CustomEvent('ra:staff-access-reset')));assert.equal(await page.locator('.food-database-modal').count(),0);checks++;
  await page.evaluate(()=>{window.allowed=false;window.RA_FOOD_DATABASE.open();});assert.equal(await page.locator('.food-database-modal').count(),0);checks++;
  assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,viewports:[1440,768,390],errors,hostedWrites:0}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
