const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function server(){return {snapshot:{version:1,fields:{},section:0,section_label:'Introduction',percent:0,pathway:'Adult'},revision:0,status:'draft',requests:[],fail:false,delay:0,finals:0};}
async function page(s,mode='mail'){
 const d=new JSDOM(fs.readFileSync(path.join(root,'consult.html'),'utf8'),{url:'https://assessment.invalid/consult.html',runScripts:'outside-only'}),w=d.window,doc=w.document;
 w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.CSS={escape:v=>String(v).replace(/[^a-zA-Z0-9_-]/g,c=>'\\'+c)};
 w.RVA_ENV={edgeBaseUrl:'https://edge.invalid',supabaseKey:'public-test'};
 const identity={first_name:'Synthetic',last_name:'Participant',email:'test@example.invalid',phone:'0000000000'};
 if(mode==='mail')w.RVA_RESUME_LINK='a'.repeat(64);if(mode==='session')w.sessionStorage.setItem('rva_vitality_session_v1','b'.repeat(64));
 w.fetch=async(url,opt)=>{
  if(url==='/'){s.requests.push({action:'lead'});return {ok:true,status:200};}
  const body=JSON.parse(opt.body);s.requests.push(body);if(s.delay)await sleep(s.delay);
  let data={status:s.status,draft_id:'synthetic-draft',identity,snapshot:structuredClone(s.snapshot),revision:s.revision};
  if(body.action==='start'||body.action==='recover')data={ok:true,message:'If an unfinished assessment is available, we’ll email a secure link.'};
  if(body.action==='redeem')data.token='b'.repeat(64);
  if(body.action==='save'){
   if(s.fail)return {ok:false,json:async()=>({error:'We couldn’t save your latest changes. Please try again.'})};
   if(body.revision!==s.revision)return {ok:false,json:async()=>({error:'Revision conflict'})};
   s.snapshot=structuredClone(body.snapshot);s.revision++;data={...data,snapshot:s.snapshot,revision:s.revision};
  }
  if(body.action==='finalize'){if(s.status!=='completed')s.finals++;s.status='completed';data={status:'completed'};}
  return {ok:true,status:200,json:async()=>data};
 };
 for(const file of ['vitality-child.js','vitality55.js','vitality-resume.js'])w.eval(fs.readFileSync(path.join(root,'js',file),'utf8'));
 await sleep(5);
 const form=doc.querySelector('[data-assessment-form]');
 function set(name,value,choice){const list=Array.from(form.querySelectorAll(`[name="${name}"]`));const c=choice?list.find(c=>c.value===choice):list[0];assert(c,name);if(['checkbox','radio'].includes(c.type))c.checked=Boolean(value);else c.value=value;c.dispatchEvent(new w.Event('input',{bubbles:true}));c.dispatchEvent(new w.Event('change',{bubbles:true}));return c;}
 return {d,w,doc,form,set,flush:()=>w.RVA_RESUME.flush(),close:()=>d.window.close()};
}
test('first contact capture remains independent and health entry waits for verified email',async()=>{const s=server(),p=await page(s,'none');const lead=p.doc.querySelector('[data-vitality-lead-form]');for(const[k,v]of Object.entries({first_name:'Synthetic',last_name:'Lead',email:'test@example.invalid',phone:'0000000000'}))lead.elements[k].value=v;lead.dispatchEvent(new p.w.Event('submit',{bubbles:true,cancelable:true}));await sleep(5);assert.deepEqual(s.requests.map(r=>r.action),['lead','start']);assert.equal(p.doc.querySelector('[data-assessment-step]').hidden,true);assert.match(p.doc.querySelector('[data-resume-notice]').textContent,/verify your email/);p.close();});
test('no raw answers are written to browser storage',async()=>{const p=await page(server());p.set('additional_context','Synthetic private context');await p.flush();assert.equal(p.w.localStorage.length,0);assert.equal(p.w.sessionStorage.length,1);assert.equal(p.w.sessionStorage.getItem('rva_vitality_session_v1'),'b'.repeat(64));p.close();});
test('debounce coalesces repeated text input and only acknowledges a server save',async()=>{const s=server(),p=await page(s);p.set('additional_context','S');p.set('additional_context','Synthetic');assert.match(p.doc.querySelector('[data-resume-status]').textContent,/Saving/);assert.equal(s.requests.filter(r=>r.action==='save').length,0);await sleep(750);assert.equal(s.requests.filter(r=>r.action==='save').length,1);assert.equal(p.doc.querySelector('[data-resume-status]').textContent,'Saved');p.close();});
for(const [label,name,value,choice]of [['radio','assessment_for',true,'Myself'],['checkbox','primary_goals',true,'Energy'],['text','additional_context','Synthetic text'],['range-zero','overall_quality_of_life','0']])test(label+' restores after a new document using server state',async()=>{const s=server(),a=await page(s);const control=a.set(name,value,choice);const expected=control.type==='checkbox'||control.type==='radio'?control.checked:control.value;await a.flush();a.close();const b=await page(s,'session');const c=choice?Array.from(b.form.querySelectorAll(`[name="${name}"]`)).find(c=>c.value===choice):b.form.elements[name];assert.equal(['checkbox','radio'].includes(c.type)?c.checked:c.value,expected);b.close();});
test('numeric zero remains numeric and blank numeric remains blank',async()=>{const s=server(),p=await page(s);p.set('assessment_for',true,'My child');p.set('assessed_age','0');await p.flush();assert.equal(s.snapshot.fields.assessed_age[0].value,0);p.set('assessed_age','');await p.flush();assert.equal(s.snapshot.fields.assessed_age[0].value,'');p.close();});
test('child pathway, guardian permission and conditional proxy details restore',async()=>{const s=server(),p=await page(s);p.set('assessment_for',true,'My child');p.set('assessed_first_name','Synthetic');p.set('assessed_last_name','Child');p.set('assessed_age','8');p.set('assessment_authorization',true);await p.flush();assert.equal(s.snapshot.pathway,'Child (ages 0–18)');p.close();const b=await page(s,'session');assert.equal(b.form.elements.assessment_pathway.value,'Child (ages 0–18)');assert.equal(b.form.elements.assessment_authorization.checked,true);assert.equal(b.form.elements.assessed_first_name.value,'Synthetic');b.close();});
test('adult proxy and permission restore without requiring paid membership',async()=>{const s=server(),a=await page(s);a.set('assessment_for',true,'Someone else');a.set('assessed_age','45');a.set('assessed_first_name','Synthetic');a.set('assessed_last_name','Adult');a.set('assessed_relationship','Sibling');a.set('assessment_authorization',true);await a.flush();a.close();const b=await page(s,'session');assert.equal(b.form.elements.assessed_relationship.value,'Sibling');assert.equal(b.form.elements.assessment_authorization.checked,true);assert.equal(b.form.elements.assessment_pathway.value,'Adult');b.close();});
test('dynamic symptom detail restores after its controlling checkbox creates the fields',async()=>{const s=server(),a=await page(s);a.set('assessment_for',true,'Myself');const screen=a.form.querySelector('[data-symptom-screen]'),box=Array.from(screen.querySelectorAll('input[type=checkbox]')).find(c=>c.value!=='None of these');a.set(box.name,true,box.value);const detail=screen.querySelector('[data-symptom-details] select');a.set(detail.name,detail.options[1].value);const name=detail.name,value=detail.value;await a.flush();a.close();const b=await page(s,'session');assert.equal(b.form.elements[name].value,value);b.close();});
test('section and progress restore after Continue and browser-style close',async()=>{const s=server(),a=await page(s);a.set('assessment_for',true,'Myself');a.set('assessment_consent',true);a.set('disclaimer_acknowledgment',true);a.doc.querySelector('[data-next]').click();await sleep(10);await a.flush();assert.equal(s.snapshot.section,1);assert(s.snapshot.percent>0);a.close();const b=await page(s,'session');assert.equal(b.w.RVA_VITALITY.section(),1);assert.equal(b.doc.querySelector('[data-progress-percent]').textContent,s.snapshot.percent+'%');b.close();});
test('failed autosave retains current answers and Retry succeeds without false Saved',async()=>{const s=server(),a=await page(s);s.fail=true;a.set('additional_context','Keep this synthetic answer');assert.equal(await a.flush(),false);assert.match(a.doc.querySelector('[data-resume-status]').textContent,/couldn’t save/);assert.equal(a.form.elements.additional_context.value,'Keep this synthetic answer');s.fail=false;assert.equal(await a.flush(),true);assert.equal(a.doc.querySelector('[data-resume-status]').textContent,'Saved');a.close();});
test('edits during an outstanding save are serialized and latest content is persisted',async()=>{const s=server(),a=await page(s);s.delay=30;a.set('additional_context','First');const pending=a.flush();a.set('additional_context','Second');await pending;assert.equal(s.snapshot.fields.additional_context[0].value,'Second');assert.equal(s.revision,2);a.close();});
test('continue later flushes before sending recovery request',async()=>{const s=server(),a=await page(s);a.set('additional_context','Later');a.doc.querySelector('[data-continue-later]').click();await sleep(15);assert.deepEqual(s.requests.slice(-2).map(r=>r.action),['save','recover']);a.close();});
test('email-only recovery never restores answers directly',async()=>{const s=server(),a=await page(s,'none');const f=a.doc.querySelector('[data-resume-request]');f.elements.resume_email.value='test@example.invalid';f.dispatchEvent(new a.w.Event('submit',{bubbles:true,cancelable:true}));await sleep(5);assert.equal(a.doc.querySelector('[data-assessment-step]').hidden,true);assert.equal(s.requests[0].action,'recover');a.close();});
test('required fields still block section navigation after resume',async()=>{const a=await page(server());a.doc.querySelector('[data-next]').click();await sleep(5);assert.equal(a.w.RVA_VITALITY.section(),0);assert.equal(a.doc.querySelector('[data-assessment-error]').classList.contains('show'),true);a.close();});
test('completed state cannot reopen editable fields and shows 100 percent',async()=>{const s=server();s.status='completed';const a=await page(s,'session');assert.equal(a.doc.querySelector('[data-assessment-step]').hidden,true);assert.equal(a.doc.querySelector('[data-complete-step]').hidden,false);assert.equal(a.doc.querySelector('[data-progress-percent]').textContent,'100%');assert.equal(a.w.RVA_RESUME.canEdit(),false);a.close();});
test('final submission is routed through the secure contract and locks the form',async()=>{const s=server(),a=await page(s);await a.w.RVA_RESUME.finalize('form-name=vitality-assessment&email=test%40example.invalid&assessment_summary=Synthetic');assert.equal(s.finals,1);assert.equal(a.w.RVA_RESUME.canEdit(),false);assert.equal(a.doc.querySelector('[data-complete-step]').hidden,false);a.close();});
test('normal final submission after server restoration retains coach summary and completes once',async()=>{
 const s=server();let p=await page(s);
 p.set('assessment_for',true,'Myself');p.set('assessment_consent',true);p.set('disclaimer_acknowledgment',true);
 p.doc.querySelector('[data-next]').click();await sleep(15);await p.flush();p.close();p=await page(s,'session');
 for(let step=0;step<35&&p.doc.querySelector('[data-complete-step]').hidden;step++){
  const panel=p.form.querySelector('[data-panel]:not([hidden])');assert(panel);
  const active=c=>!c.disabled&&!c.closest('[hidden]');
  for(const name of ['reproductive_screen_path','hormone_pathway']){const c=Array.from(panel.querySelectorAll(`[name="${name}"]`)).find(c=>c.tagName==='SELECT'||c.value==='Male');if(c&&active(c))p.set(name,c.type==='radio'?true:'Male',c.type==='radio'?'Male':undefined);}
  for(const screen of panel.querySelectorAll('[data-symptom-screen]')){if(!active(screen))continue;const c=Array.from(screen.querySelectorAll('input')).find(c=>c.value==='None of these');if(c)p.set(c.name,true,c.value);}
  const goals=panel.querySelector('[name="primary_goals"]');if(goals&&active(goals))p.set(goals.name,true,goals.value);
  for(const c of panel.querySelectorAll('[required]')){if(!active(c)||c.checkValidity())continue;p.set(c.name,['checkbox','radio'].includes(c.type)?true:c.tagName==='SELECT'?c.options[1].value:'Synthetic answer',['checkbox','radio'].includes(c.type)?c.value:undefined);}
  const before=p.w.RVA_VITALITY.section();p.doc.querySelector('[data-next]').click();await sleep(15);await p.flush();
  assert(p.w.RVA_VITALITY.section()!==before||!p.doc.querySelector('[data-complete-step]').hidden,p.doc.querySelector('[data-assessment-error]').textContent);
 }
 assert.equal(s.finals,1);const final=s.requests.find(r=>r.action==='finalize'),data=new URLSearchParams(final.form);assert.match(data.get('assessment_summary'),/Synthetic/);assert.equal(data.get('form-name'),'vitality-assessment');assert.equal(data.get('assessment_for'),'Myself');assert.equal(p.doc.querySelector('[data-progress-percent]').textContent,'100%');p.close();
});
