import {edgeEnvironment,assertSyntheticRecipient,assertNotification} from '../../supabase/functions/_shared/environment.ts';
import {handleRequest} from '../../supabase/functions/member-account/handler.ts';
const vars:Record<string,string>={RVA_ENVIRONMENT:'staging',SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',RVA_APP_ORIGIN:'https://beta.revitalizedacademy.com',RVA_FALLBACK_ORIGINS:'https://revitalizedacademy-staging.netlify.app',RVA_PAYMENT_MODE:'synthetic',RVA_SYNTHETIC_EMAIL_ALLOWLIST:'synthetic@example.invalid'};
function assert(ok:unknown){if(!ok)throw Error('Assertion failed');}
function rejects(fn:()=>unknown){let threw=false;try{fn();}catch{threw=true;}assert(threw);}
Deno.test('Edge explicit staging origins keep the Netlify fallback while invitations and recovery use branded beta',()=>{const c=edgeEnvironment(k=>vars[k]);assert(c.allowedOrigins.length===2&&c.allowedOrigins[0]===vars.RVA_APP_ORIGIN&&c.allowedOrigins[1]===vars.RVA_FALLBACK_ORIGINS);assert(c.recoveryRedirect===vars.RVA_APP_ORIGIN+'/portal/password-reset.html');assert(c.signerUrl===vars.RVA_APP_ORIGIN+'/member/onboarding/');});
for(const [name,patch]of Object.entries({missing:{RVA_ENVIRONMENT:''},project:{SUPABASE_URL:'https://voalfpxiyznnqfcqcymd.supabase.co'},origin:{RVA_APP_ORIGIN:'https://revitalizedacademy.com'},runtime:{DENO_DEPLOYMENT_ID:'voalfpxiyznnqfcqcymd_function_1'},payments:{RVA_PAYMENT_MODE:'live'}}))Deno.test('Edge refuses '+name,()=>rejects(()=>edgeEnvironment(k=>(({...vars,...patch} as Record<string,string|undefined>)[k]))));
Deno.test('Edge rejects wrong configuration before any Supabase request',async()=>{const saved=Deno.env.get,fetch=globalThis.fetch;let calls=0;Deno.env.get=()=>undefined;globalThis.fetch=()=>{calls++;throw Error('must not call');};try{const r=await handleRequest(new Request('https://edge.invalid',{method:'POST'}));assert(r.status===503&&calls===0);}finally{Deno.env.get=saved;globalThis.fetch=fetch;}});
Deno.test('staging delivery rejects real recipients, foreign callback origins and SMS',()=>{const saved=Deno.env.get;Deno.env.get=k=>vars[k];try{assertSyntheticRecipient('synthetic@example.invalid');rejects(()=>assertSyntheticRecipient('client@example.com'));assertNotification({recipient:'synthetic@example.invalid',body:vars.RVA_APP_ORIGIN+'/member/onboarding/#invite=synthetic',channel:'email'});rejects(()=>assertNotification({recipient:'synthetic@example.invalid',body:'https://revitalizedacademy.com/member/',channel:'email'}));rejects(()=>assertNotification({recipient:'synthetic@example.invalid',channel:'sms'}));}finally{Deno.env.get=saved;}});
Deno.test('production origin mapping stays explicit',()=>{const c=edgeEnvironment(k=>({...vars,RVA_ENVIRONMENT:'production',SUPABASE_URL:'https://voalfpxiyznnqfcqcymd.supabase.co',RVA_APP_ORIGIN:'https://revitalizedacademy.com'}[k]));assert(c.allowedOrigins.includes('https://www.revitalizedacademy.com'));});
