import {createHandler as recovery} from '../../supabase/functions/member-password-reset/handler.ts';
import {createHandler as delivery} from '../../supabase/functions/client-lifecycle-delivery/handler.ts';
function assert(value:unknown):asserts value{if(!value)throw Error('Assertion failed');}
async function fixture(work:()=>Promise<void>){const old=Deno.env.get;Deno.env.get=key=>({RVA_ENVIRONMENT:'production',SUPABASE_URL:'https://voalfpxiyznnqfcqcymd.supabase.co',RVA_APP_ORIGIN:'https://revitalizedacademy.com'}[key]);try{await work();}finally{Deno.env.get=old;}}
const req=(body:unknown,origin='https://revitalizedacademy.com')=>new Request('https://voalfpxiyznnqfcqcymd.supabase.co/functions/v1/test',{method:'POST',headers:{origin,Authorization:'Bearer local-fixture','content-type':'application/json'},body:JSON.stringify(body)});
for(const scenario of ['eligible','missing','limited','provider-failed'])Deno.test('recovery neutral response: '+scenario,()=>fixture(async()=>{
 const calls:string[]=[];const handler=recovery({reserve:async()=>{calls.push('reserve');return scenario!=='limited';},eligible:async email=>{calls.push(email);return scenario!=='missing';},generate:async()=>{calls.push('generate');return 'https://revitalizedacademy.com/member/password-reset.html?token_hash=LOCAL-SECRET';},mail:async()=>{calls.push('mail');if(scenario==='provider-failed')throw Error('LOCAL-SECRET');}});
 const result=await handler(req({email:' New@EXAMPLE.INVALID '})),data=await result.json();assert(result.status===200&&data.ok&&data.message.includes('If that email'));assert(!JSON.stringify(data).includes('LOCAL-SECRET'));assert(calls[0]==='reserve');assert(scenario!=='limited'||calls.length===1);
}));
Deno.test('recovery rejects foreign origin before identity/provider access',()=>fixture(async()=>{const handler=recovery({reserve:async()=>{throw Error('must not call');},eligible:async()=>false,generate:async()=>'',mail:async()=>{}});assert((await handler(req({email:'x@y.invalid'},'https://beta.revitalizedacademy.com'))).status===403);}));
Deno.test('recovery rejects forged non-production reset action',()=>fixture(async()=>{let sent=false;const handler=recovery({reserve:async()=>true,eligible:async()=>true,generate:async()=> 'https://beta.revitalizedacademy.com/member/password-reset.html?token_hash=secret',mail:async()=>{sent=true;}});assert((await handler(req({email:'x@y.invalid'}))).status===200&&!sent);}));
for(const kind of ['normal','already-processed','unauthorized','provider-failed','beta-url'])Deno.test('agreement dispatcher '+kind,()=>fixture(async()=>{
 const finishes:any[]=[];let sends=0;const handler=delivery({user:async()=>kind==='unauthorized'?null:'owner',claim:async()=>kind==='already-processed'?null:{id:'job',recipient:'local@example.invalid',subject:'Agreement',body:(kind==='beta-url'?'https://beta.revitalizedacademy.com':'https://revitalizedacademy.com')+'/member/onboarding/#enroll=LOCAL-SECRET'},send:async()=>{sends++;if(kind==='provider-failed')throw Error('LOCAL-SECRET');return 'provider-id';},finish:async(...args)=>{finishes.push(args);}});
 const result=await handler(req({client_agreement_id:'12345678-1234-4234-8234-123456789012'})),text=await result.text();assert(!text.includes('LOCAL-SECRET'));
 if(kind==='normal'){assert(sends===1&&finishes[0][2]==='provider-id'&&result.status===200);}if(kind==='unauthorized')assert(result.status===401&&sends===0);if(kind==='already-processed')assert(sends===0);if(kind==='provider-failed'||kind==='beta-url')assert(result.status===502&&finishes[0][2]===null);
}));
Deno.test('agreement dispatcher cannot send malformed ID or foreign-origin request',()=>fixture(async()=>{const handler=delivery({user:async()=> 'owner',claim:async()=>{throw Error('must not call');},send:async()=>'',finish:async()=>{}});assert((await handler(req({client_agreement_id:'bad'}))).status===400);assert((await handler(req({},'https://beta.revitalizedacademy.com'))).status===403);}));
Deno.test('legacy activation no longer creates or auto-verifies Auth users; requires caller-verified claim',()=>fixture(async()=>{
 const {createHandler}=await import('../../supabase/functions/member-account/handler.ts');const calls:any[]=[];
 const handler=createHandler({verified:async()=>true,claim:async(...args)=>{calls.push(args);}});const token='a'.repeat(64);
 assert((await handler(req({token,password:'must-never-be-used',email:'different@example.invalid'}))).status===200);assert(calls.length===1&&calls[0][0]==='local-fixture'&&calls[0][1]===token);
 const get=new Request('https://voalfpxiyznnqfcqcymd.supabase.co/functions/v1/member-account?token='+token,{headers:{origin:'https://revitalizedacademy.com'}});assert((await handler(get)).status===405);
}));
Deno.test('legacy activation cannot claim an unverified account',()=>fixture(async()=>{const {createHandler}=await import('../../supabase/functions/member-account/handler.ts');const handler=createHandler({verified:async()=>false,claim:async()=>{throw Error('must not call');}});assert((await handler(req({token:'a'.repeat(64)}))).status===401);}));
Deno.test('legacy signing cannot forge two adult signatures or replace the expected content hash',()=>fixture(async()=>{
 const {createHandler}=await import('../../supabase/functions/agreement-sign/handler.ts'),calls:any[]=[];const handler=createHandler({verified:async()=>true,rpc:async(...args)=>{calls.push(args);}}),id='12345678-1234-4234-8234-123456789012';
 const base={action:'sign',client_agreement_id:id,accepted_terms:true,expected_content_hash:'current-hash',signatures:[{signer_role:'primary_client',signer_name:'Local Adult'}]};
 assert((await handler(req({...base,signatures:[...base.signatures,...base.signatures]}))).status===400);assert(calls.length===0);
 assert((await handler(req(base))).status===200);assert(calls[0][0]==='local-fixture'&&calls[0][1]==='sign_client_agreement_atomic'&&calls[0][2].p_expected_content_hash==='current-hash');
}));
Deno.test('legacy signing denies unverified users and never exposes backend errors',()=>fixture(async()=>{const {createHandler}=await import('../../supabase/functions/agreement-sign/handler.ts');let valid=false;const handler=createHandler({verified:async()=>valid,rpc:async()=>{throw Error('PRIVATE-ANSWERS');}}),body={action:'view',client_agreement_id:'12345678-1234-4234-8234-123456789012'};assert((await handler(req(body))).status===401);valid=true;const r=await handler(req(body));assert(r.status===409&&!(await r.text()).includes('PRIVATE-ANSWERS'));}));
