import {createHandler,opaque,digest,validSnapshot,assessmentTags} from '../../supabase/functions/vitality-resume/handler.ts';
function assert(v:unknown,message='Assertion failed'):asserts v{if(!v)throw Error(message);}
const token='a'.repeat(64),snapshot={version:1,section:0,section_label:'Intro',percent:0,pathway:'Adult',fields:{answer:[{type:'number',value:0}]}};
async function run(body:any,options:{origin?:string;eligible?:boolean;mailFail?:boolean;finalFail?:boolean;rpcFail?:boolean;status?:string}={}){
 const old=Deno.env.get;Deno.env.get=k=>({RVA_ENVIRONMENT:'local',RVA_APP_ORIGIN:'https://synthetic.invalid',RVA_PAYMENT_MODE:'synthetic',RVA_SYNTHETIC_EMAIL_ALLOWLIST:'test@example.invalid',SUPABASE_URL:'https://synthetic.invalid'}[k]);
 const calls:any[]=[],mails:any[]=[],finals:string[]=[];
 const handler=createHandler({rpc:async(action,hash,next,payload)=>{calls.push({action,hash,next,payload});if(options.rpcFail)throw {code:'42501',message:'RAW-'+token+' sensitive payload'};if(action==='start'||action==='recover')return options.eligible===false?{}:{recipient:'test@example.invalid'};if(action==='cancel_mail')return{};if(action==='prepare_final')return {status:options.status||'dispatch'};if(action==='finish_final')return{status:'completed'};return{status:options.status||'draft',draft_id:'draft-a',identity:{email:'test@example.invalid'},revision:0,snapshot};},mail:async(to,url)=>{mails.push({to,url});if(options.mailFail)throw Error('private-provider-error');},final:async(form)=>{finals.push(form);if(options.finalFail)throw Error('private-provider-error');}});
 try{const r=await handler(new Request('https://synthetic.invalid/function',{method:'POST',headers:{origin:options.origin||'https://synthetic.invalid','content-type':'application/json'},body:JSON.stringify(body)}));return{status:r.status,data:await r.json(),calls,mails,finals};}finally{Deno.env.get=old;}
}
Deno.test('opaque tokens contain 256 bits and hashes differ from raw credentials',async()=>{const a=opaque(),b=opaque();assert(/^[a-f0-9]{64}$/.test(a)&&a!==b);assert(await digest(a)!==a);});
Deno.test('start stores only token digest and returns neutral response without draft/answers/token',async()=>{const r=await run({action:'start',email:'test@example.invalid',first_name:'Synthetic',last_name:'Person',phone:'0000000000'});assert(r.status===200&&r.mails.length===1);const raw=r.mails[0].url.split('#resume=')[1];assert(r.calls[0].next===await digest(raw));assert(!JSON.stringify(r.calls).includes(raw));assert(!r.data.token&&!r.data.snapshot&&!r.data.draft_id);});
Deno.test('recover response does not disclose whether eligible draft exists',async()=>{const a=await run({action:'recover',email:'test@example.invalid'}),b=await run({action:'recover',email:'test@example.invalid'},{eligible:false});assert(JSON.stringify(a.data)===JSON.stringify(b.data));assert(b.mails.length===0);});
Deno.test('staging recipient restriction preserved',async()=>{const r=await run({action:'recover',email:'unapproved@example.invalid'});assert(r.status===200&&r.calls.length===0&&r.mails.length===0);});
Deno.test('foreign origin cannot make draft or provider calls',async()=>{const r=await run({action:'read',token},{origin:'https://wrong.invalid'});assert(r.status===403&&r.calls.length===0);});
Deno.test('random malformed credential rejected before database access',async()=>{const r=await run({action:'read',token:'guess'});assert(r.status===401&&r.calls.length===0);});
Deno.test('database errors never leak tokens or answers to response',async()=>{const r=await run({action:'read',token},{rpcFail:true});assert(r.status===401&&!JSON.stringify(r.data).includes(token)&&!JSON.stringify(r.data).includes('sensitive'));});
Deno.test('redemption replaces emailed credential with new opaque session token',async()=>{const r=await run({action:'redeem',token});assert(r.data.token!==token&&/^[a-f0-9]{64}$/.test(r.data.token));assert(r.calls[0].hash===await digest(token)&&r.calls[0].next===await digest(r.data.token));});
Deno.test('snapshot validates zero but rejects invalid versions, nonfinite values and oversized text',()=>{assert(validSnapshot(snapshot));assert(!validSnapshot({...snapshot,version:2}));assert(!validSnapshot({...snapshot,fields:{x:[{type:'number',value:NaN}]}}));assert(!validSnapshot({...snapshot,fields:{x:[{type:'text',value:'x'.repeat(15001)}]}}));});
Deno.test('save forwards exact expected draft and revision to scoped transaction',async()=>{const r=await run({action:'save',token,draft_id:'draft-b',revision:0,snapshot});assert(r.calls[0].payload.draft_id==='draft-b'&&r.calls[0].payload.revision===0);});
Deno.test('failed mail revokes only unredeemed mail digest',async()=>{const r=await run({action:'recover',email:'test@example.invalid'},{mailFail:true});assert(r.calls[1].action==='cancel_mail'&&r.calls[1].hash===r.calls[0].next);assert(!JSON.stringify(r.data).includes('private-provider'));});
const form='form-name=vitality-assessment&email=test%40example.invalid&assessment_summary=Synthetic';
Deno.test('final submission dispatches once through ticketed transaction',async()=>{const r=await run({action:'finalize',token,revision:0,form});assert(r.finals.length===1&&r.calls.map(c=>c.action).join(',')==='read,prepare_final,finish_final');assert(r.finals[0].includes('assessment_resume_id=draft-a'));});
Deno.test('finalization of completed draft never sends another assessment',async()=>{const r=await run({action:'finalize',token,revision:0,form},{status:'completed'});assert(r.data.status==='completed'&&r.finals.length===0);});
Deno.test('uncertain transport locks finalization instead of retrying an external write',async()=>{const r=await run({action:'finalize',token,revision:0,form},{finalFail:true});assert(r.status===409&&r.finals.length===1&&r.calls.at(-1).action==='uncertain_final');});
Deno.test('final assessment cannot replace the verified respondent email',async()=>{const r=await run({action:'finalize',token,revision:0,form:form.replace('test%40','other%40')});assert(r.status===400&&r.finals.length===0);});

Deno.test('mail failure has the same neutral recovery response as an unknown email',async()=>{const failed=await run({action:'recover',email:'test@example.invalid'},{mailFail:true});const absent=await run({action:'recover',email:'test@example.invalid'},{eligible:false});assert(failed.status===absent.status&&JSON.stringify(failed.data)===JSON.stringify(absent.data));});
Deno.test('approved derived tags use saved selections and relevant text only',()=>{const tags=assessmentTags({fields:{symptoms:[{type:'checkbox',value:'Poor sleep',checked:true},{type:'checkbox',value:'Pain',checked:false}],goal:[{type:'textarea',value:'More energy'}],name:[{type:'text',value:'fatigue'}]}});assert(tags.includes('concern:sleep')&&tags.includes('goal:energy')&&!tags.includes('concern:pain')&&!tags.includes('concern:fatigue'));});
