select jsonb_build_object(
'tables',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'acl',c.relacl,'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind='r'),
'constraints',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',co.conname,'type',co.contype,'definition',pg_get_constraintdef(co.oid,true))) from pg_constraint co join pg_class c on c.oid=co.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','private')),
'indexes',(select jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'name',indexname,'definition',indexdef)) from pg_indexes where schemaname in('public','private')),
'types',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',t.typname,'kind',t.typtype,'labels',(select jsonb_agg(e.enumlabel order by e.enumsortorder) from pg_enum e where e.enumtypid=t.oid))) from pg_type t join pg_namespace n on n.oid=t.typnamespace where n.nspname in('public','private') and t.typtype in('e','d')),
'extensions',(select jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname)) from pg_extension e join pg_namespace n on n.oid=e.extnamespace),
'views',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'options',c.reloptions,'acl',c.relacl,'definition',pg_get_viewdef(c.oid,true))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','private') and c.relkind='v'),
'functions',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'acl',p.proacl,'definition',pg_get_functiondef(p.oid))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','private') and p.prokind='f' and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')),
'triggers',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid,true))) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname in('public','private','auth')),
'policies',(select jsonb_agg(to_jsonb(p)) from pg_policies p where schemaname in('public','private','storage')),
'grants',(select jsonb_agg(to_jsonb(g)) from information_schema.role_table_grants g where table_schema in('public','private','storage')),
'schema_acl',(select jsonb_agg(jsonb_build_object('schema',nspname,'acl',nspacl)) from pg_namespace where nspname in('public','private')),
'defaults',(select jsonb_agg(jsonb_build_object('role',pg_get_userbyid(defaclrole),'schema',n.nspname,'type',defaclobjtype,'acl',defaclacl)) from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace),
'sequences',(select jsonb_agg(to_jsonb(s)) from pg_sequences s where schemaname in('public','private')),
'migrations',(select jsonb_agg(jsonb_build_object('version',version,'name',name,'statement_count',cardinality(statements),'statement_md5',md5(array_to_string(statements,E'\n'))) order by version) from supabase_migrations.schema_migrations),
'buckets',(select jsonb_agg(jsonb_build_object('id',id,'public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types)) from storage.buckets)
) as snapshot;