const fs=require('fs'),cp=require('child_process'),crypto=require('crypto'),assert=require('assert/strict');const dir=__dirname;
const cli='/Users/davesmacbookpro/.npm/_npx/da5c1b6ea715e8b4/node_modules/.bin/netlify';const stage='071b252e-a922-4846-a784-8dca1edad377',production='ece0f6f3-6c3d-46e6-bb51-95ce1ccefb06';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const write=(name,data)=>fs.writeFileSync(dir+'/'+name,JSON.stringify(data,null,2)+'\n');
function site(id){const s=JSON.parse(cp.execFileSync(cli,['api','getSite','--data',JSON.stringify({site_id:id})],{encoding:'utf8',maxBuffer:8e6}));return{id:s.id,name:s.name,url:s.ssl_url,deploy:s.published_deploy?.id,commit:s.published_deploy?.commit_ref,repo:s.build_settings?.repo_path,branch:s.build_settings?.repo_branch,build:s.build_settings?.cmd,publish:s.build_settings?.dir};}
const paths=['/','/consult.html','/js/vitality55.js','/js/vitality-child.js','/js/revitalized-data.js','/css/vitality55.css','/runtime-config.js','/portal/','/member/'];
async function get(url){const r=await fetch(url,{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(30000)});const bytes=Buffer.from(await r.arrayBuffer());return{status:r.status,sha256:hash(bytes),bytes};}
async function productionSnapshot(){return Promise.all(paths.map(async p=>{const{bytes,...r}=await get('https://revitalizedacademy.com'+p);return{path:p,...r};}));}
(async()=>{
 if(process.argv[2]==='before'){const s=site(stage);assert.equal(s.name,'revitalizedacademy-staging');write('deployment-before.json',{at:new Date().toISOString(),staging:s,production:site(production),productionFiles:await productionSnapshot()});console.log('Staging target verified; production deployment and nine public fingerprints captured.');}
 else if(process.argv[2]==='after'){const before=require('./deployment-before.json'),prod=site(production),now=await productionSnapshot();assert.equal(prod.deploy,before.production.deploy);assert.deepEqual(now,before.productionFiles);const assets=['/js/vitality55.js?v=resume-1','/js/vitality-resume.js?v=1','/js/revitalized-data.js?v=20261005','/css/vitality55.css?v=86','/js/vitality-child.js?v=nodash-20260921','/runtime-config.js'];const live=await Promise.all(assets.map(async p=>{const{bytes,...r}=await get('https://revitalizedacademy-staging.netlify.app'+p);assert.equal(r.status,200);assert.equal(r.sha256,hash(fs.readFileSync('dist'+p.split('?')[0])));return{path:p,...r,exactBuild:true};}));const html=await get('https://revitalizedacademy-staging.netlify.app/consult.html');assert.equal(html.status,200);assert(html.bytes.toString().includes('js/vitality-resume.js?v=1'));write('deployment-after.json',{at:new Date().toISOString(),staging:site(stage),production:prod,productionUnchanged:true,assets:live});console.log('All six assets match build; production deployment and nine fingerprints unchanged.');}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
