const {test,before,after,beforeEach,afterEach}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{Client}=require('pg'),contract=require('../../netlify/lib/content-sync-contract.json');
if(!/^rva_sync_production_\d+$/.test(process.env.RVA_SYNC_PRODUCTION_DB||'')||!/^rva_sync_beta_\d+$/.test(process.env.RVA_SYNC_BETA_DB||''))throw Error('Disposable local sync fixtures required');
const conn={host:'127.0.0.1',port:Number(process.env.RVA_SYNC_PGPORT),user:'postgres'},prod=new Client({...conn,database:process.env.RVA_SYNC_PRODUCTION_DB}),beta=new Client({...conn,database:process.env.RVA_SYNC_BETA_DB});let owners,ids;
const value=async(db,sql,args=[])=>Object.values((await db.query(sql,args)).rows[0])[0];
async function role(db,who,sql,args=[],r='service_role'){await db.query('savepoint call');try{await db.query('set local role '+r);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[who||'']);const result=await db.query(sql,args.map(a=>Array.isArray(a)?JSON.stringify(a):a));await db.query('reset role');await db.query('release call');return Object.values(result.rows[0]||{})[0];}catch(e){await db.query('rollback to call');await db.query('release call');throw e;}}
async function user(r){const id=randomUUID();await prod.query('insert into auth.users(id,email) values($1,$2)',[id,id+'@example.invalid']);if(r){await prod.query("insert into staff_access(user_id,role,status,onboarding_status,contact_scope) values($1,$2,'active','complete','all')",[id,r]);await prod.query("update staff_access set onboarding_status='complete' where user_id=$1",[id]);}return id;}
async function insert(db,table,data){const entries=Object.entries(data);return value(db,'insert into public.'+table+'('+entries.map(([k])=>k).join(',')+') values('+entries.map((_,i)=>'$'+(i+1)).join(',')+') returning id',entries.map(([,v])=>v));}
async function exported(records=roots(),actor=owners.owner){return role(prod,null,'select public.reusable_content_sync_server($1,\'export\',$2)',[actor,records]);}
async function receive(batch){return role(beta,null,'select public.receive_production_content($1)',[batch]);}
async function finish(batch,result){return role(prod,null,'select public.reusable_content_sync_server($1,\'complete\',null,$2,$3)',[owners.owner,batch.job_id,result]);}
const roots=()=>['food_catalog:food','food_catalog:usda','recipes:recipe','meal_plan_templates:meal','exercise_catalog:exercise','workout_templates:workout','fitness_programs:program'].map(s=>{const [type,key]=s.split(':');return {type,id:ids[key]};});
before(async()=>{await prod.connect();await beta.connect();});after(async()=>{await prod.end();await beta.end();});
beforeEach(async()=>{
 await prod.query('begin');await beta.query('begin');await prod.query("insert into staff_permission_catalog(permission_key,label,category) values('learning.manage','Content','Learning') on conflict do nothing");await prod.query("insert into staff_role_permission_defaults(role,permission_key,allowed) values('owner','learning.manage',true),('admin','learning.manage',true),('coach','learning.manage',true) on conflict(role,permission_key) do update set allowed=true");owners={owner:await user('owner'),admin:await user('admin'),coach:await user('coach'),member:await user(null)};ids={};
 ids.nutrition=await insert(prod,'nutrition_methodologies',{methodology_key:'qa-nutrition',name:'QA Nutrition',created_by:owners.owner,metadata:{client_id:'private-sentinel'}});ids.phase=await insert(prod,'nutrition_phases',{methodology_id:ids.nutrition,phase_key:'first',name:'First Phase',phase_order:1});ids.fitness=await insert(prod,'fitness_methodologies',{methodology_key:'qa-fitness',name:'QA Fitness',created_by:owners.owner});
 ids.food=await insert(prod,'food_catalog',{methodology_id:ids.nutrition,phase_id:ids.phase,name:'QA Custom Food',nutrition:{protein_g:0,fiber_g:1},grams_per_serving:100,active:true});
 const normalized=require('../../netlify/lib/fooddata.cjs').normalize(require('../fixtures/usda-foods.json').foods[0]);ids.usda=(await role(prod,null,'select public.food_database_server($1,\'import\',null,$2,$3)',[owners.owner,normalized,ids.nutrition])).id;
 ids.recipe=await insert(prod,'recipes',{methodology_id:ids.nutrition,title:'QA Recipe',servings:2});ids.ingredient=await insert(prod,'recipe_ingredients',{recipe_id:ids.recipe,food_id:ids.food,ingredient:'Custom food',quantity:100,unit:'g'});await insert(prod,'recipe_ingredients',{recipe_id:ids.recipe,food_id:ids.usda,ingredient:'Apple',quantity:100,unit:'g'});await role(prod,owners.owner,'select public.recalculate_recipe_nutrition($1)',[ids.recipe],'authenticated');
 ids.meal=await insert(prod,'meal_plan_templates',{methodology_id:ids.nutrition,title:'QA Meal Plan',days_count:1});ids.mealItem=await insert(prod,'meal_plan_template_items',{template_id:ids.meal,day_number:1,meal_slot:'breakfast',recipe_id:ids.recipe});
 ids.exercise=await insert(prod,'exercise_catalog',{methodology_id:ids.fitness,name:'QA Exercise',category:'strength',environment:'either'});ids.workout=await insert(prod,'workout_templates',{methodology_id:ids.fitness,title:'QA Workout',category:'strength',environment:'either'});ids.composition=await insert(prod,'workout_template_exercises',{workout_id:ids.workout,exercise_id:ids.exercise,sort_order:1,sets:2,reps:10});ids.program=await insert(prod,'fitness_programs',{methodology_id:ids.fitness,title:'QA Fitness Program',weeks:1,environment:'either'});ids.schedule=await insert(prod,'fitness_program_workouts',{program_id:ids.program,workout_id:ids.workout,week_number:1,day_number:1});
});afterEach(async()=>{await prod.query('rollback');await beta.query('rollback');});
test('all seven roots transfer dependency trees with remapped references, real nutrition and audit',async()=>{
 const batch=await exported(),result=await receive(batch);assert.equal(result.length,15);assert.equal(batch.nodes.length,15);await finish(batch,result);
 for(const type of Object.keys(contract)){assert(batch.nodes.some(n=>n.type===type),type);const sourceIds=batch.nodes.filter(n=>n.type===type).map(n=>n.source_id);const copied=(await beta.query('select * from public.'+type+' where id in (select target_id from production_content_sources where content_type=$1)',[type])).rows;assert.equal(copied.length,sourceIds.length);for(const row of copied){assert(!sourceIds.includes(row.id));assert(row.created_by===null||row.created_by===undefined);}}
 assert.equal(Number(await value(beta,'select count(*) from auth.users')),0);assert.equal(Number(await value(beta,'select count(*) from public.contacts')),0);assert.equal(Number(await value(beta,'select count(*) from staff_access')),0);assert(!JSON.stringify(batch).includes('private-sentinel'));assert(!batch.nodes.some(n=>Object.keys(JSON.parse(n.data_serialized)).includes('created_by')));
 const ingredient=(await beta.query('select * from recipe_ingredients order by ingredient')).rows[0];assert.equal(ingredient.food_id,ingredient.nutrition_snapshot.food_id);
 const nutrition=await value(beta,'select nutrition from recipes');assert.deepEqual(nutrition,await value(prod,'select nutrition from recipes'));assert.equal(nutrition.energy_kcal,undefined);assert.equal(nutrition.protein_g,Math.round(require('../../netlify/lib/fooddata.cjs').normalize(require('../fixtures/usda-foods.json').foods[0]).nutrition.protein_g/2*1e6)/1e6);
 assert.equal(Number(await value(prod,"select count(*) from private.reusable_content_sync_audit where result='complete'")),15);assert.equal(Number(await value(beta,'select count(*) from private.reusable_content_receive_audit')),15);
});
test('repeat and exact-job retry are idempotent; beta edits do not write back; later production wins',async()=>{
 const first=await exported(),result=await receive(first);assert.deepEqual(await receive(first),result);const initial=(await beta.query('select content_type,source_id,target_id from production_content_sources order by content_type,source_id')).rows;
 const recipe=result.find(n=>n.type==='recipes').target_id;await beta.query("update recipes set title='Beta-only edit' where id=$1",[recipe]);assert.equal(await value(prod,'select title from recipes'),'QA Recipe');
 await prod.query("update recipes set title='Production authoritative update' where id=$1",[ids.recipe]);const later=await exported();await receive(later);assert.equal(await value(beta,'select title from recipes'),'Production authoritative update');assert.deepEqual((await beta.query('select content_type,source_id,target_id from production_content_sources order by content_type,source_id')).rows,initial);assert.equal(Number(await value(beta,'select count(*) from food_catalog')),2);
 const changed=structuredClone(first);changed.actor_id=randomUUID();await assert.rejects(receive(changed),/payload mismatch/);const resumed=await role(prod,null,"select public.reusable_content_sync_server($1,'resume',null,$2)",[owners.owner,first.job_id]);assert.deepEqual(resumed,first);
});
test('Owner/Admin allowed; Coach/member/anonymous/browser RPC and reverse denied',async()=>{
 for(const actor of [owners.owner,owners.admin])assert.equal((await role(prod,null,"select public.reusable_content_sync_server($1,'authorize')",[actor])).authorized,true);
 for(const actor of [owners.coach,owners.member,null])await assert.rejects(role(prod,null,"select public.reusable_content_sync_server($1,'authorize')",[actor]),/Owner\/Admin/);
 for(const r of ['authenticated','anon']){await assert.rejects(role(prod,owners.owner,"select public.reusable_content_sync_server($1,'authorize')",[owners.owner],r),/permission denied/);await assert.rejects(role(beta,owners.owner,'select public.receive_production_content($1)',[{}],r),/permission denied/);}
 await assert.rejects(beta.query("select public.reusable_content_sync_server($1,'authorize')",[owners.owner]),/does not exist/);await assert.rejects(prod.query('select public.receive_production_content($1)',[{}]),/does not exist/);
});
test('private/operational tables and disallowed identity fields are rejected atomically',async()=>{
 for(const type of ['contacts','staff_access','vitality_reports','nutrition_diary_items','meal_plan_assignments','payments','client_agreements'])await assert.rejects(exported([{type,id:ids.food}]),/Unsupported/);
 const batch=await exported();const tampered=JSON.parse(batch.nodes[0].data_serialized);tampered.client_id=randomUUID();batch.nodes[0].data_serialized=JSON.stringify(tampered);batch.nodes[0].version=await value(prod,'select md5($1::jsonb::text)',[tampered]);await assert.rejects(receive(batch),/Invalid|Disallowed/);assert.equal(Number(await value(beta,'select count(*) from food_catalog')),0);
});
test('missing dependencies roll back every beta write; failed and stale syncs are audited/denied',async()=>{
 const batch=await exported();batch.nodes=batch.nodes.filter(n=>n.type!=='food_catalog');await assert.rejects(receive(batch),/Missing synced/);assert.equal(Number(await value(beta,"select count(*) from nutrition_methodologies where methodology_key='qa-nutrition'")),0);
 await role(prod,null,"select public.reusable_content_sync_server($1,'failed',null,$2)",[owners.owner,batch.job_id]);assert.equal(Number(await value(prod,"select count(*) from private.reusable_content_sync_audit where result='failed'")),15);
 const fresh=await exported();await receive(fresh);const stale=await exported();stale.exported_at='2020-01-01T00:00:00Z';await assert.rejects(receive(stale),/newer production sync/);
});
test('obsolete composition is removed only from mapped copies; new canonical schedule retains mapping',async()=>{
 const initial=await exported();await receive(initial);await prod.query('delete from workout_template_exercises where id=$1',[ids.composition]);const updated=await exported();await receive(updated);assert.equal(Number(await value(beta,'select count(*) from workout_template_exercises')),0);assert.equal(Number(await value(beta,"select count(*) from private.reusable_content_receive_audit where result='obsolete_composition_removed'")),1);
 await prod.query('delete from fitness_program_workouts where id=$1',[ids.schedule]);await insert(prod,'fitness_program_workouts',{program_id:ids.program,workout_id:ids.workout,week_number:1,day_number:1});await receive(await exported());assert.equal(Number(await value(beta,'select count(*) from fitness_program_workouts')),1);
});

test('RepDB Exercise, Workout and Program dependency sync preserve source/local data and stable mapping',async()=>{
 const normalized=require('../../netlify/lib/repdb.cjs').normalize(require('../../netlify/private-repdb/exercises.json').exercises[0]);const ex=await role(prod,null,"select public.exercise_library_server($1,'import',$2,$3)",[owners.owner,normalized,ids.fitness]);await prod.query("update exercise_catalog set revitalized_approved=true,functional_movement='Core',coaching_cues='Local owned cue' where id=$1",[ex.id]);await prod.query('update workout_template_exercises set exercise_id=$1 where id=$2',[ex.id,ids.composition]);let target;
 for(const type of ['exercise_catalog','workout_templates','fitness_programs']){const id=type==='exercise_catalog'?ex.id:type==='workout_templates'?ids.workout:ids.program;const result=await receive(await exported([{type,id}]));const current=result.find(n=>n.type==='exercise_catalog').target_id;if(target)assert.equal(current,target);target=current;const b=(await beta.query('select * from exercise_catalog where id=$1',[target])).rows[0];assert.equal(b.provider_exercise_id,normalized.id);assert.equal(b.exercise_source.version,normalized.version);assert.equal(b.revitalized_approved,true);assert.equal(b.functional_movement,'Core');assert.equal(b.coaching_cues,'Local owned cue');}
 await beta.query("update exercise_catalog set coaching_cues='Beta edit' where id=$1",[target]);assert.equal(await value(prod,'select coaching_cues from exercise_catalog where id=$1',[ex.id]),'Local owned cue');await receive(await exported([{type:'exercise_catalog',id:ex.id}]));assert.equal(await value(beta,'select coaching_cues from exercise_catalog where id=$1',[target]),'Local owned cue');assert.equal(Number(await value(beta,"select count(*) from exercise_catalog where exercise_provider='repdb'")),1);
});

test('production sync reuses a separately imported beta RepDB slug without creating a duplicate',async()=>{
 const src=require('../../netlify/lib/repdb.cjs').normalize(require('../../netlify/private-repdb/exercises.json').exercises[0]);const ex=await role(prod,null,"select public.exercise_library_server($1,'import',$2,$3)",[owners.owner,src,ids.fitness]);const method=await insert(beta,'fitness_methodologies',{methodology_key:'beta-only-local',name:'Local beta method',status:'draft'});const local=await insert(beta,'exercise_catalog',{methodology_id:method,name:'Beta local display name',category:'strength',exercise_provider:'repdb',provider_exercise_id:src.id,exercise_source_version:src.version,exercise_source:src});
 const result=await receive(await exported([{type:'exercise_catalog',id:ex.id}]));assert.equal(result.find(x=>x.type==='exercise_catalog').target_id,local);assert.equal(Number(await value(beta,"select count(*) from exercise_catalog where exercise_provider='repdb' and provider_exercise_id=$1",[src.id])),1);assert.equal(await value(beta,'select name from exercise_catalog where id=$1',[local]),ex.name);
});

test('RepDB sync preserves an unrelated beta custom exercise with the same display name',async()=>{
 const src=require('../../netlify/lib/repdb.cjs').normalize(require('../../netlify/private-repdb/exercises.json').exercises[0]);const ex=await role(prod,null,"select public.exercise_library_server($1,'import',$2,$3)",[owners.owner,src,ids.fitness]);const method=await insert(beta,'fitness_methodologies',{methodology_key:'qa-fitness',name:'QA Fitness'});const custom=await insert(beta,'exercise_catalog',{methodology_id:method,name:ex.name,category:'strength',coaching_cues:'Beta custom keep'});const batch=await exported([{type:'exercise_catalog',id:ex.id}]);const result=await receive(batch),target=result.find(x=>x.type==='exercise_catalog').target_id;assert.notEqual(target,custom);const old=(await beta.query('select * from exercise_catalog where id=$1',[custom])).rows[0];assert.equal(old.exercise_provider,null);assert.equal(old.coaching_cues,'Beta custom keep');assert.equal(old.name,ex.name);assert.notEqual(await value(beta,'select name from exercise_catalog where id=$1',[target]),ex.name);await receive(await exported([{type:'exercise_catalog',id:ex.id}]));assert.equal(Number(await value(beta,'select count(*) from exercise_catalog')),2);
});

test('compatible beta receiver accepts old complete exercise exports but rejects partial new provenance',async()=>{
 const batch=await exported([{type:'workout_templates',id:ids.workout}]);const n=batch.nodes.find(x=>x.type==='exercise_catalog'),d=JSON.parse(n.data_serialized),newFields=['exercise_provider','provider_exercise_id','exercise_source_version','exercise_source','exercise_imported_at','revitalized_approved','rva_muscles','functional_movement','coaching_cues'];for(const f of newFields)delete d[f];n.data_serialized=JSON.stringify(d);n.version=await value(prod,'select md5($1::jsonb::text)',[d]);const result=await receive(batch);const target=result.find(x=>x.type==='exercise_catalog').target_id;assert.equal(await value(beta,'select exercise_provider from exercise_catalog where id=$1',[target]),null);assert.equal(Number(await value(beta,'select count(*) from workout_template_exercises')),1);
 const partial=await exported([{type:'exercise_catalog',id:ids.exercise}]);const x=partial.nodes.find(x=>x.type==='exercise_catalog'),v=JSON.parse(x.data_serialized);delete v.coaching_cues;x.data_serialized=JSON.stringify(v);x.version=await value(prod,'select md5($1::jsonb::text)',[v]);await assert.rejects(receive(partial),/Incomplete content node/);
});

test('custom production exercise sync never replaces a same-name beta RepDB import',async()=>{
 const src=require('../../netlify/lib/repdb.cjs').normalize(require('../../netlify/private-repdb/exercises.json').exercises[0]);const method=await insert(beta,'fitness_methodologies',{methodology_key:'qa-fitness',name:'QA Fitness'}),existing=await insert(beta,'exercise_catalog',{methodology_id:method,name:'QA Exercise',category:'strength',exercise_provider:'repdb',provider_exercise_id:src.id,exercise_source_version:src.version,exercise_source:src});const result=await receive(await exported([{type:'exercise_catalog',id:ids.exercise}])),custom=result.find(x=>x.type==='exercise_catalog').target_id;assert.notEqual(custom,existing);assert.equal(await value(beta,'select provider_exercise_id from exercise_catalog where id=$1',[existing]),src.id);assert.equal(await value(beta,'select exercise_provider from exercise_catalog where id=$1',[custom]),null);assert.equal(Number(await value(beta,'select count(*) from exercise_catalog')),2);
});
