// Eight independent PostgreSQL sessions released by a server advisory barrier.
const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID,createHash}=require('node:crypto'),{Client}=require('pg');
if(!/^rva_gate_\d+_\d+$/.test(process.env.RVA_TEST_DATABASE||'')||process.env.PGHOST!=='127.0.0.1')throw Error('Disposable local database required');
async function race(db,actor,sql,args,role='authenticated'){
 const gate=33499001,workers=Array.from({length:8},()=>new Client({application_name:'rva_lifecycle_overlap'}));
 try{await Promise.all(workers.map(c=>c.connect()));await db.query('select pg_advisory_lock($1)',[gate]);
  const pids=await Promise.all(workers.map(async c=>(await c.query('select pg_backend_pid() pid')).rows[0].pid));assert.equal(new Set(pids).size,8);
  const operations=workers.map(async c=>{await c.query('begin');await c.query('set local role '+role);await c.query("select set_config('request.jwt.claim.sub',$1,true),set_config('request.jwt.claim.role',$2,true)",[actor||'',role]);await c.query('select pg_advisory_xact_lock_shared($1)',[gate]);try{const r=await c.query(sql,args);await c.query('commit');return r.rows[0];}catch(e){await c.query('rollback');throw e;}});
  let overlap=0;for(let i=0;i<200;i++){overlap=Number((await db.query("select count(*) n from pg_stat_activity where application_name='rva_lifecycle_overlap' and wait_event='advisory'")).rows[0].n);if(overlap===8)break;await new Promise(r=>setTimeout(r,10));}
  assert.equal(overlap,8,'all workers must overlap at the server barrier');await db.query('select pg_advisory_unlock($1)',[gate]);const results=await Promise.all(operations);return {pids,overlap,results};
 }finally{await db.query('select pg_advisory_unlock_all()');await Promise.allSettled(workers.map(c=>c.end()));}
}
test('true overlap: one contact, one enrollment, one immutable signature, one dispatch lease',async()=>{
 const db=new Client();await db.connect();try{
 const meta=require('../../../revitalizedacademy/supabase/baselines/2026-09-26/metadata.json');for(const row of meta.permission_catalog){const keys=Object.keys(row);await db.query('insert into staff_permission_catalog('+keys.join(',')+') values('+keys.map((_,i)=>'$'+(i+1)).join(',')+') on conflict do nothing',Object.values(row));}for(const row of meta.permission_defaults)await db.query('insert into staff_role_permission_defaults(role,permission_key,allowed) values($1,$2,$3) on conflict do nothing',[row.role,row.permission_key,row.allowed]);
 const owner=randomUUID();await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[owner,owner+'@example.invalid']);await db.query("insert into staff_access(user_id,role,status,onboarding_status,contact_scope) values($1,'owner','active','complete','all')",[owner]);await db.query("update staff_access set onboarding_status='complete' where user_id=$1",[owner]);
 await db.query("insert into journey_definitions(journey_key,name,audience) values('direct_membership','Local membership','client') on conflict do nothing");await db.query("insert into journey_step_definitions(journey_key,step_key,step_order,name,step_type,required) values('direct_membership','application_capture',1,'Contact','form',true),('direct_membership','payment_agreement',2,'Agreement','form',true) on conflict do nothing");
 const email=randomUUID()+'@example.invalid',request=randomUUID();const creation=await race(db,owner,'select public.create_production_client($1,$2) id',[request,{first_name:'Overlap',last_name:'Fixture',email,phone:'5559997878',referral_source:'Google Search'}]);const contact=creation.results[0].id;assert.ok(creation.results.every(r=>r.id===contact));assert.equal(Number((await db.query('select count(*) n from contacts where email=$1',[email])).rows[0].n),1);
 const enrollment=await race(db,owner,"select public.save_production_client_enrollment($1,'holistic-foundations','monthly',8900,'CAD') state",[contact]);assert.equal(Number((await db.query('select count(*) n from journey_enrollment_activations where contact_id=$1',[contact])).rows[0].n),1);
 const client=randomUUID();await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[client,email]);await db.query('update client_access set user_id=$2,needs_onboarding_claim=false where contact_id=$1',[contact,client]);
 await db.query("update app_runtime_config set config_value='{\"status\":\"released\",\"reason\":\"local_test_only\"}' where config_key='production_client_agreement_publication'");const content='Disposable local agreement for {{client_name}}',hash=createHash('sha256').update(content).digest('hex');const template=(await db.query("insert into agreement_templates(agreement_key,name,version,content_text,content_hash,status,audience,document_type,merge_schema) values($1,'Local concurrency agreement','local',$2,$3,'published','client','client_contract','{\"required\":[\"client_name\"],\"optional\":[]}') returning id",[randomUUID(),content,hash])).rows[0].id;await db.query("insert into program_agreement_requirements(program_code,agreement_template_id,required,active,billing_choice,currency) values('holistic-foundations',$1,true,true,'monthly','CAD')",[template]);
 await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role','authenticated',false)",[owner]);const agreement=(await db.query('select public.prepare_client_contract($1,$2,$3,true) id',[contact,template,{client_name:'Local Adult'}])).rows[0].id;await db.query("select set_config('request.jwt.claim.sub','',false)");const rendered=(await db.query('select rendered_content_hash from client_agreements where id=$1',[agreement])).rows[0].rendered_content_hash;
 const signatures=await race(db,client,'select public.sign_client_agreement_atomic($1,$2,$3) id',[agreement,JSON.stringify([{signer_role:'primary_client',signer_name:'Local Adult'}]),rendered]);assert.ok(signatures.results.every(r=>r.id===signatures.results[0].id));assert.equal(Number((await db.query('select count(*) n from agreement_acceptances where client_agreement_id=$1',[agreement])).rows[0].n),1);
 const dispatch=await race(db,null,'select public.claim_production_agreement_delivery($1,$2) job',[owner,agreement],'service_role');assert.equal(dispatch.results.filter(r=>r.job!==null).length,1);
 assert.equal(Number((await db.query('select count(*) n from payment_records')).rows[0].n),0);
 console.log(JSON.stringify({groups:4,workers:8,overlap:8,distinctBackendPids:creation.pids.length,contact:1,enrollment:1,signature:1,deliveryLease:1}));
 }finally{await db.end();}
});
