const {test,before,after,beforeEach,afterEach}=require('node:test');
const assert=require('node:assert/strict');const {Client}=require('pg');const {randomBytes}=require('node:crypto');
if(!/^rva_gate_\d+_\d+$/.test(process.env.RVA_TEST_DATABASE||''))throw Error('Disposable database required');
const db=new Client(),q=(s,p=[])=>db.query(s,p),val=async(s,p)=>{const v=Object.values((await q(s,p)).rows[0])[0];return typeof v==='string'&&/^\d+$/.test(v)?Number(v):v;};
const hash=()=>randomBytes(32).toString('hex');
const cmd=(a,h=null,n=null,p={})=>val('select public.vitality_resume_command($1,$2,$3,$4)',[a,h,n,p]);
const identity=email=>({email,first_name:'Synthetic',last_name:'Assessment',phone:'0000000000',referral_source:'Google Search',sales_rep_name:'',referral_source_other:''});
const snapshot={version:1,section:2,section_label:'Synthetic section',percent:13,pathway:'Adult',fields:{zero:[{type:'number',value:0}],multi:[{type:'checkbox',value:'A',checked:false}],text:[{type:'textarea',value:'Synthetic text'}]}};
async function start(email='a@example.invalid'){const mail=hash(),session=hash();await cmd('start',null,mail,identity(email));const draft=await cmd('redeem',mail,session,{});return {mail,session,draft};}
async function rejected(sql,params=[],pattern=/./){await q('savepoint denied');try{await assert.rejects(q(sql,params),pattern);}finally{await q('rollback to denied');await q('release denied');}}
before(async()=>{await db.connect();});after(()=>db.end());
beforeEach(async()=>{await q('begin');await q("insert into public.journey_definitions(journey_key,name,audience) values('assessment_first','Synthetic assessment','lead') on conflict do nothing");await q("insert into public.journey_step_definitions(journey_key,step_key,step_order,name,step_type) values('assessment_first','vitality_assessment',1,'Synthetic Vitality','assessment') on conflict do nothing");});
afterEach(()=>q('rollback'));
test('start captures one attributed contact, one unfinished draft and a workflow; email-only request exposes no answers',async()=>{const h=hash();const data=await cmd('start',null,h,identity('a@example.invalid'));assert.deepEqual(Object.keys(data),['recipient']);assert.equal(await val('select count(*) from private.vitality_assessment_drafts'),1);assert.equal(await val("select count(*) from public.contacts where email='a@example.invalid' and referral_source='Google Search' and sales_rep_name is null and referral_source_other is null"),1);assert.equal(await val("select identity->>'referral_source' from private.vitality_assessment_drafts"),'Google Search');});
test('conditional referral details persist without stale alternate detail',async()=>{const rep={...identity('rep@example.invalid'),referral_source:'Sales Rep',sales_rep_name:'Synthetic Rep',referral_source_other:'stale'};await cmd('start',null,hash(),rep);assert.equal(await val("select sales_rep_name from public.contacts where email='rep@example.invalid'"),'Synthetic Rep');assert.equal(await val("select referral_source_other is null from public.contacts where email='rep@example.invalid'"),true);await q('delete from private.vitality_resume_rate_limits');const other={...identity('other@example.invalid'),referral_source:'Other',sales_rep_name:'stale',referral_source_other:'Community partner'};await cmd('start',null,hash(),other);assert.equal(await val("select referral_source_other from public.contacts where email='other@example.invalid'"),'Community partner');assert.equal(await val("select sales_rep_name is null from public.contacts where email='other@example.invalid'"),true);});
test('request throttles repeat mail and leaves active credential intact',async()=>{const a=await start();assert.deepEqual(await cmd('recover',null,hash(),{email:'a@example.invalid'}),{});assert.equal((await cmd('read',a.session)).draft_id,a.draft.draft_id);});
test('replaying consumed email credential cannot replace the valid session or mutate existing draft/workflow',async()=>{
 const a=await start();await cmd('save',a.session,null,{revision:0,snapshot});
 const before=(await q('select id,contact_id,workflow_id,status,revision,snapshot,session_hash,session_expires_at,verified_at,recovery_hash,recovery_expires_at from private.vitality_assessment_drafts')).rows;
 assert.equal(before[0].recovery_hash,null);assert.equal(before[0].recovery_expires_at,null);
 await rejected('select public.vitality_resume_command($1,$2,$3)',['redeem',a.mail,hash()],/Resume unavailable/);
 assert.deepEqual((await q('select id,contact_id,workflow_id,status,revision,snapshot,session_hash,session_expires_at,verified_at,recovery_hash,recovery_expires_at from private.vitality_assessment_drafts')).rows,before);
 const restored=await cmd('read',a.session);assert.equal(restored.draft_id,a.draft.draft_id);assert.deepEqual(restored.snapshot,snapshot);
 assert.equal(await val('select count(*) from private.vitality_assessment_drafts'),1);
 assert.equal(await val("select count(*) from public.contacts where email='a@example.invalid'"),1);
 assert.equal(await val('select count(*) from public.workflow_records'),1);
});
test('normalization reuses contact and unfinished draft without email wildcard matching',async()=>{const a=await start('a_b@example.invalid');await q('delete from private.vitality_resume_rate_limits');await cmd('start',null,hash(),identity(' A_B@example.invalid '));assert.equal(await val('select count(*) from private.vitality_assessment_drafts'),1);await start('axb@example.invalid');assert.equal(await val('select count(*) from private.vitality_assessment_drafts'),2);assert(a.draft.draft_id);});
test('save persists typed values, current section and percentage',async()=>{const a=await start();const r=await cmd('save',a.session,null,{revision:0,snapshot});assert.deepEqual(r.snapshot,snapshot);assert.equal(r.revision,1);assert.equal(await val('select completion_percent from public.workflow_records where id=(select workflow_id from private.vitality_assessment_drafts where id=$1)',[a.draft.draft_id]),13);});
test('cross-device mail redemption returns same draft and replaces old session',async()=>{const a=await start();await cmd('save',a.session,null,{revision:0,snapshot});await q('delete from private.vitality_resume_rate_limits');const mail=hash(),session=hash();await cmd('recover',null,mail,{email:'a@example.invalid'});const r=await cmd('redeem',mail,session);assert.equal(r.draft_id,a.draft.draft_id);assert.deepEqual(r.snapshot,snapshot);await rejected('select public.vitality_resume_command($1,$2)', ['read',a.session],/Resume unavailable/);});
test('Person A cannot read Person B by supplying B draft ID',async()=>{const a=await start(),b=await start('b@example.invalid');await rejected('select public.vitality_resume_command($1,$2,null,$3)',['read',a.session,{draft_id:b.draft.draft_id}],/Resume unavailable/);});
test('Person A cannot update Person B by supplying B draft ID',async()=>{const a=await start(),b=await start('b@example.invalid');await rejected('select public.vitality_resume_command($1,$2,null,$3)',['save',a.session,{draft_id:b.draft.draft_id,revision:0,snapshot}],/Resume unavailable/);});
test('random and modified credentials denied',async()=>{await start();await rejected('select public.vitality_resume_command($1,$2)',['read',hash()],/Resume unavailable/);});
test('expired mail and expired session denied',async()=>{const a=await start();await q("update private.vitality_assessment_drafts set session_expires_at=now()-interval '1 second'");await rejected('select public.vitality_resume_command($1,$2)',['read',a.session],/Resume unavailable/);await q('delete from private.vitality_resume_rate_limits');const mail=hash();await cmd('recover',null,mail,{email:'a@example.invalid'});await q("update private.vitality_assessment_drafts set recovery_expires_at=now()-interval '1 second'");await rejected('select public.vitality_resume_command($1,$2,$3)',['redeem',mail,hash()],/Resume unavailable/);});
test('successful save refreshes thirty day session inactivity window',async()=>{const a=await start();await q("update private.vitality_assessment_drafts set session_expires_at=now()+interval '1 hour'");await cmd('save',a.session,null,{revision:0,snapshot});assert.equal(await val("select session_expires_at=now()+interval '30 days' from private.vitality_assessment_drafts"),true);});
test('revision conflict does not overwrite a newer snapshot',async()=>{const a=await start();await cmd('save',a.session,null,{revision:0,snapshot});await rejected('select public.vitality_resume_command($1,$2,null,$3)',['save',a.session,{revision:0,snapshot:{...snapshot,section:3}}],/Revision conflict/);assert.equal((await cmd('read',a.session)).snapshot.section,2);});
test('malformed snapshot rejected without modifying draft',async()=>{const a=await start();await rejected('select public.vitality_resume_command($1,$2,null,$3)',['save',a.session,{revision:0,snapshot:{version:1,fields:{}}}],/Invalid snapshot/);});
test('anonymous and authenticated direct RPC/table bypass denied',async()=>{for(const role of ['anon','authenticated']){await q('savepoint rolecheck');await q('set local role '+role);await assert.rejects(q("select public.vitality_resume_command('recover',null,null,'{}')"),/permission denied/);await q('rollback to rolecheck');await q('set local role '+role);await assert.rejects(q('select * from private.vitality_assessment_drafts'),/permission denied/);await q('rollback to rolecheck');await q('release rolecheck');}});
test('final dispatch is one-time; final completion and Journey event are idempotent',async()=>{const a=await start(),ticket=hash();const first=await cmd('prepare_final',a.session,ticket,{revision:0,form:'synthetic=only'});assert.equal(first.status,'dispatch');assert.equal((await cmd('prepare_final',a.session,hash(),{revision:0,form:'again=1'})).status,'submitting');assert.equal((await cmd('finish_final',a.session,ticket)).status,'completed');assert.equal((await cmd('finish_final',a.session,ticket)).status,'completed');assert.equal(await val("select count(*) from public.journey_events where event_type='vitality_completed'"),1);assert.equal(await val('select completion_percent from public.workflow_records where id=(select workflow_id from private.vitality_assessment_drafts)'),100);});
test('completed token reveals no answers and cannot reopen editable state',async()=>{const a=await start(),ticket=hash();await cmd('prepare_final',a.session,ticket,{revision:0,form:'synthetic=only'});await cmd('finish_final',a.session,ticket);const r=await cmd('save',a.session,null,{revision:0,snapshot});assert.equal(r.status,'completed');assert.equal(r.snapshot,undefined);assert.equal(await val("select count(*) from private.vitality_assessment_drafts where status='draft'"),0);});
test('uncertain final delivery locks retries without erasing answers',async()=>{const a=await start(),ticket=hash();await cmd('save',a.session,null,{revision:0,snapshot});await cmd('prepare_final',a.session,ticket,{revision:1,form:'synthetic=only'});await cmd('uncertain_final',a.session,ticket);assert.equal((await cmd('prepare_final',a.session,hash(),{revision:1,form:'again=1'})).status,'delivery_uncertain');assert.deepEqual(await val('select snapshot from private.vitality_assessment_drafts'),snapshot);});
test('repeated start after completion cannot duplicate or overwrite completed assessment',async()=>{const a=await start(),ticket=hash();await cmd('prepare_final',a.session,ticket,{revision:0,form:'synthetic=only'});await cmd('finish_final',a.session,ticket);await q('delete from private.vitality_resume_rate_limits');assert.deepEqual(await cmd('start',null,hash(),identity('a@example.invalid')),{});assert.equal(await val('select count(*) from private.vitality_assessment_drafts'),1);assert.equal(await val("select count(*) from public.contacts where email='a@example.invalid'"),1);assert.equal(await val('select status from public.workflow_records'),'completed');});

test('completion preserves approved derived tags and excludes unapproved tags',async()=>{const a=await start(),ticket=hash();await cmd('prepare_final',a.session,ticket,{revision:0,form:'synthetic=only'});await cmd('finish_final',a.session,ticket,{derived_tags:['goal:energy','concern:sleep','admin:owner']});assert.deepEqual((await q('select tag from public.contact_tags order by tag')).rows.map(r=>r.tag),['concern:sleep','goal:energy']);});
test('null credentials and missing progress percentage fail closed',async()=>{await rejected('select public.vitality_resume_command($1,null,null,$2)',['start',identity('a@example.invalid')],/Invalid request/);const a=await start();const {percent,...missing}=snapshot;await rejected('select public.vitality_resume_command($1,$2,null,$3)',['save',a.session,{revision:0,snapshot:missing}],/Invalid snapshot/);});
